### ISSUE TITLE
MindMap

### ISSUE THREAD

**Issue by saniok017** [saniok017/Server#3]
Разработать предварительную [MindMap](https://user-images.githubusercontent.com/39351424/57124710-6abc7f80-6d8f-11e9-869a-8fa6b64ecea3.png) проекта

**Comment by DasneiN** [comment]
![d2943d606d5c11e9a36e95a0790bab9a map](https://user-images.githubusercontent.com/3667375/57119852-0a6d1400-6d76-11e9-9f94-0f8028bcad41.png)


[Ссылка на саму MindMap](https://drive.google.com/file/d/1hUs7RRusJSolUrJ8oouMOmitsVVfGIJ9/view?usp=sharing)
